{'type':'CustomDialog',
          'name':'backgroundInfo',
          'title':'Background Info',
          'size':(370, 380),
          'components': [

{'type':'StaticText', 
    'name':'stcName', 
    'position':(10, 10), 
    'text':'Name:', 
    },

{'type':'StaticText', 
    'name':'stcTitle', 
    'position':(10, 35), 
    'text':'Title:', 
    },

{'type':'StaticText', 
    'name':'stcPosition', 
    'position':(10, 60), 
    'text':'Position:', 
    },

{'type':'StaticText', 
    'name':'stcSize', 
    'position':(10, 85), 
    'text':'Size:', 
    },

{'type':'StaticText', 
    'name':'stcForegroundColor', 
    'position':(10, 110), 
    'text':'Foreground color:', 
    },

{'type':'StaticText', 
    'name':'stcBackgroundColor', 
    'position':(10, 135), 
    #'size':(90, -1), 
    'text':'Background color:', 
    },

{'type':'StaticText', 
    'name':'stcImage', 
    'position':(10, 160), 
    'text':'Image:', 
    },

{'type':'StaticText', 
    'name':'stcIcon', 
    'position':(10, 210), 
    'text':'Icon:', 
    },

{'type':'TextField', 
    'name':'fldName', 
    'position':(130, 5), 
    },

{'type':'TextField', 
    'name':'fldTitle', 
    'position':(130, 30), 
    'size':(188, -1), 
    },

{'type':'TextField', 
    'name':'fldPosition', 
    'position':(130, 55), 
    'size':(80, -1), 
    },

{'type':'TextField', 
    'name':'fldSize', 
    'position':(130, 80), 
    'size':(80, -1), 
    },

{'type':'TextField', 
    'name':'fldForegroundColor', 
    'position':(130, 110), 
    'size':(100, -1), 
    },

{'type':'Button', 
    'name':'btnForegroundColor', 
    'position':(250, 110), 
    'label':'Color...',
    },

{'type':'TextField', 
    'name':'fldBackgroundColor', 
    'position':(130, 135), 
    'size':(100, -1), 
    },

{'type':'Button', 
    'name':'btnBackgroundColor', 
    'position':(250, 135), 
    'label':'Color...',
    },

{'type':'TextField', 
    'name':'fldImage', 
    'position':(130, 160), 
    'size':(100, -1), 
    },

{'type':'Button', 
    'name':'btnFile', 
    'position':(250, 160), 
    'label':'File...',
    },

{'type':'CheckBox', 
    'name':'chkTiled', 
    'position':(130, 185), 
    'size':(135, -1), 
    'checked':0, 
    'label':'Tile image', 
    },

{'type':'TextField', 
    'name':'fldIcon', 
    'position':(130, 210), 
    'size':(100, -1), 
    },

{'type':'Button', 
    'name':'btnIconFile', 
    'position':(250, 210), 
    'label':'File...',
    },

{'type':'CheckBox', 
    'name':'chkStatusBar', 
    'position':(130, 235), 
    'checked':0, 
    'label':'Status bar on window', 
    },

{'type':'CheckBox', 
    'name':'chkVisible', 
    'position':(130, 260), 
    'size':(135, -1), 
    'checked':1, 
    'label':'Visible at startup', 
    },

{'type':'CheckBox', 
    'name':'chkResizeable', 
    'position':(130, 285), 
    'size':(135, -1), 
    'checked':0, 
    'label':'Resizeable', 
    },

{'type':'Button', 
    'name':'btnOK', 
    'position':(10, 320), 
    'label':'OK',
    'default':1,
    'id':5100,
    },

{'type':'Button', 
    'name':'btnCancel', 
    'position':(115, 320), 
    'label':'Cancel',
    'id':5101,
    },

] # end components
} # end CustomDialog
