{'type':'CustomDialog',
    'name':'menuDialog',
    'title':'Menu Editor',
    'size':(480, 300),
    'components': [

{'type':'List', 
    'name':'listMenus', 
    'position':(0, 0), 
    'size':(185, 185), 
    'items':[], 
    },

{'type':'Button', 
    'name':'btnUp', 
    'position':(5, 190), 
    'size':(50, -1), 
    'label':'Up', 
    },

{'type':'Button', 
    'name':'btnDown', 
    'position':(60, 190), 
    'size':(60, -1), 
    'label':'Down', 
    },

{'type':'Button', 
    'name':'btnDelete', 
    'position':(125, 190), 
    'size':(60, -1), 
    'label':'Delete', 
    },

{'type':'StaticText', 
    'name':'stcName', 
    'position':(200, 10), 
    'text':'Name:', 
    },

{'type':'StaticText', 
    'name':'stcLabel', 
    'position':(200, 35), 
    'text':'Label:', 
    },

{'type':'StaticText', 
    'name':'stcShortcut', 
    'position':(200, 60), 
    'text':'Shortcut:', 
    },

{'type':'StaticText', 
    'name':'stcCommand', 
    'position':(200, 85), 
    'text':'Command:', 
    },

{'type':'TextField', 
    'name':'fldListIndex', 
    'position':(460, 5), 
    'visible':False, 
    },

{'type':'TextField', 
    'name':'fldName', 
    'position':(275, 5), 
    'size':(188, -1), 
    },

{'type':'TextField', 
    'name':'fldLabel', 
    'position':(275, 30), 
    'size':(188, -1), 
    },

{'type':'TextField', 
    'name':'fldShortcut', 
    'position':(275, 55), 
    'size':(188, -1), 
    },

{'type':'TextField', 
    'name':'fldCommand', 
    'position':(275, 80), 
    'size':(188, -1), 
    },

{'type':'CheckBox', 
    'name':'chkEnabled', 
    'position':(275, 110), 
    'checked':True, 
    'label':'Enabled', 
    },

{'type':'CheckBox', 
    'name':'chkCheckable', 
    'position':(275, 135), 
    'label':'Checkable', 
    },

{'type':'CheckBox', 
    'name':'chkChecked', 
    'position':(275, 160), 
    'label':'Checked', 
    },

{'type':'Button', 
    'name':'btnNewMenu', 
    'position':(220, 190), 
    'label':'New Menu', 
    },

{'type':'Button', 
    'name':'btnNewMenuItem', 
    'position':(320, 190), 
    'label':'New MenuItem', 
    },

{'type':'Button', 
    'id':5100, 
    'name':'btnOK', 
    'position':(10, 240), 
    'default':1, 
    'label':'OK', 
    },

{'type':'Button', 
    'id':5101, 
    'name':'btnCancel', 
    'position':(115, 240), 
    'label':'Cancel', 
    },

] # end components
} # end CustomDialog
