@ECHO OFF
REM This file was generated by 'PatternWorkbook'  1759076147.1476617

@ECHO OFF
REM Upload hex-file to  ATTiny
REM ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
REM
REM   Hex-File:              DM-TinyServo.hex
REM

REM Schwarz auf Ocker
COLOR 60

ECHO Hochladen Hexfile fuer den ATTiny
ECHO ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ECHO Der ATTiny85 muss dazu in die Tiny_UniProg Platine gesteckt sein.
ECHO Dieser Vorgang muss nur ein mal gemacht werden. Danach wird nur noch die geaenderte
ECHO Konfiguration vom Pattern_Configuartor aus zum ATTiny geschickt.
ECHO.

SET DefaultPort=5
SET ComPort=%1
IF NOT "%ComPort%" == "" Goto PortIsSet
   SET /P PortNr=COM port Nummer an den der Tiny_UniProg angeschlossen ist [%DefaultPort%]:
   IF "%PortNr%" == "" SET PortNr=%DefaultPort%
   SET ComPort=\\.\COM%PortNr%
:PortIsSet


"%USERPROFILE%\AppData\Local\Arduino15\packages/arduino/tools/avrdude/6.3.0-arduino17/bin/avrdude.exe" ^
    "-C%USERPROFILE%\AppData\Local\Arduino15\packages\ATTinyCore\hardware\avr\1.5.2\avrdude.conf"  ^
    -v -pattiny85 -c avrisp -P%ComPort% -b19200 ^
    -U flash:w:DM-TinyServo.hex:i



IF ERRORLEVEL 1 (
    ECHO Error hochladen ;-(
    ECHO Starting second try
    "%USERPROFILE%\AppData\Local\Arduino15\packages/arduino/tools/avrdude/6.3.0-arduino17/bin/avrdude.exe" ^
        "-C%USERPROFILE%\AppData\Local\Arduino15\packages\ATTinyCore\hardware\avr\1.5.2\avrdude.conf"  ^
        -v -pattiny85 -c avrisp  -P%ComPort% -b19200 ^
        -U flash:w:DM-TinyServo.hex:i

   )

IF ERRORLEVEL 1 (
    ECHO Error setting the fuses ;-(((
    ECHO Starting third try
    "%USERPROFILE%\AppData\Local\Arduino15\packages/arduino/tools/avrdude/6.3.0-arduino17/bin/avrdude.exe" ^
        "-C%USERPROFILE%\AppData\Local\Arduino15\packages\ATTinyCore\hardware\avr\1.5.2\avrdude.conf"  ^
        -v -pattiny85 -c avrisp -P%ComPort% -b19200 ^
        -Uflash:w:DM-TinyServo.hex:i

   )

IF ERRORLEVEL 1 (
   REM White on RED
   COLOR 4F
   ECHO Set_Fuses Result: %ERRORLEVEL% > "Upload_Hex_result.txt"
   ECHO   *********************************************
   ECHO  * Da ist was schief gegangen ;-(            *              ERRORLEVEL %ERRORLEVEL%
   ECHO   *********************************************
   Pause
   )
