{'type':'CustomDialog',
    'name':'Template',
    'title':'New Project Wizard',
    'position':(171, 401),
    'size':(600, 330),
    'components': [

{'type':'Image', 
    'name':'Image1', 
    'position':(-5, -5), 
    'size':(174, 324), 
    'file':'pixmaps/newproject.png', 
    },

{'type':'Button', 
    'name':'backBtn', 
    'position':(330, 275), 
    'enabled':False, 
    'label':'< Back', 
    },

{'type':'Button', 
    'name':'nextBtn', 
    'position':(415, 275), 
    'label':'Next >', 
    },

{'type':'Button', 
    'id':5101, 
    'name':'cancelBtn', 
    'position':(510, 275), 
    'label':'Cancel', 
    },

{'type':'StaticText', 
    'name':'page0text1', 
    'position':(175, 0), 
    'font':{'faceName': 'Tahoma', 'family': 'sansSerif', 'size': 20}, 
    'text':'Welcome to the new project', 
    'userdata':'page0', 
    },

{'type':'StaticText', 
    'name':'page0text2', 
    'position':(175, 30), 
    'font':{'faceName': 'Tahoma', 'family': 'sansSerif', 'size': 20}, 
    'text':'wizard!', 
    'userdata':'page0', 
    },

{'type':'StaticText', 
    'name':'page0text3', 
    'position':(175, 85), 
    'font':{'faceName': 'Tahoma', 'family': 'sansSerif', 'size': 10}, 
    'text':'This will gather the information required to create a brand new project.', 
    'userdata':'page0', 
    },

{'type':'StaticText', 
    'name':'page0text4', 
    'position':(175, 100), 
    'font':{'faceName': 'Tahoma', 'family': 'sansSerif', 'size': 10}, 
    'text':'Click Next to continue, or Cancel to exit the wizard.', 
    'userdata':'page0', 
    },

] # end components
} # end CustomDialog
