{'application':{'type':'Application',
          'name':'Template',
    'backgrounds': [
    {'type':'Background',
          'name':'outputWindow',
          'title':'Rebuild project',
          'size':(400, 300),
          'visible':0,

         'components': [

{'type':'TextArea', 
    'name':'importError', 
    'position':(10, 10), 
    'size':(375, 205), 
    'actionBindings':{}, 
    'editable':False, 
    'enabled':False, 
    'visible':False, 
    },

{'type':'Button', 
    'name':'clipBoardBtn', 
    'position':(95, 225), 
    'actionBindings':{}, 
    'label':'Clipboard', 
    'toolTip':'Click here to copy the PythonCard component imports line to the Windows clipboard', 
    },

{'type':'Button', 
    'name':'closeBtn', 
    'position':(10, 225), 
    'actionBindings':{}, 
    'label':'Close', 
    },

{'type':'StaticText', 
    'name':'txt5', 
    'position':(10, 90), 
    'actionBindings':{}, 
    'text':'Returned messages:', 
    },

{'type':'TextArea', 
    'name':'returnedText', 
    'position':(10, 105), 
    'size':(375, 110), 
    'actionBindings':{}, 
    },

{'type':'StaticText', 
    'name':'txt4c', 
    'position':(145, 70), 
    'actionBindings':{}, 
    'text':'please wait...', 
    'visible':False, 
    },

{'type':'StaticText', 
    'name':'txt4b', 
    'position':(145, 70), 
    'actionBindings':{}, 
    'font':{'style': 'bold', 'faceName': 'Verdana', 'family': 'sansSerif', 'size': 8}, 
    'text':'Done', 
    'visible':False, 
    },

{'type':'StaticText', 
    'name':'txt4a', 
    'position':(10, 70), 
    'actionBindings':{}, 
    'text':'Rebuilding distributable:', 
    'visible':False, 
    },

{'type':'StaticText', 
    'name':'txt3c', 
    'position':(145, 50), 
    'actionBindings':{}, 
    'text':'please wait...', 
    'visible':False, 
    },

{'type':'StaticText', 
    'name':'txt3b', 
    'position':(145, 50), 
    'actionBindings':{}, 
    'font':{'style': 'bold', 'faceName': 'Verdana', 'family': 'sansSerif', 'size': 8}, 
    'text':'Done', 
    'visible':False, 
    },

{'type':'StaticText', 
    'name':'txt3a', 
    'position':(10, 50), 
    'actionBindings':{}, 
    'text':'Rebuilding application:', 
    'visible':False, 
    },

{'type':'StaticText', 
    'name':'txt2b', 
    'position':(145, 30), 
    'actionBindings':{}, 
    'font':{'style': 'bold', 'faceName': 'Verdana', 'family': 'sansSerif', 'size': 8}, 
    'text':'Done', 
    'visible':False, 
    },

{'type':'StaticText', 
    'name':'txt2a', 
    'position':(10, 30), 
    'actionBindings':{}, 
    'text':'Rebuilding versioninfo file:', 
    'visible':False, 
    },

{'type':'StaticText', 
    'name':'txt1b', 
    'position':(145, 10), 
    'actionBindings':{}, 
    'font':{'style': 'bold', 'faceName': 'Verdana', 'family': 'sansSerif', 'size': 8}, 
    'text':'Done', 
    'visible':False, 
    },

{'type':'StaticText', 
    'name':'txt1a', 
    'position':(10, 10), 
    'actionBindings':{}, 
    'text':'Rebuilding spec file:', 
    'visible':False, 
    },

] # end components
} # end background
] # end backgrounds
} }
