{'type':'CustomDialog',
    'name':'prefsDialog',
    'title':'standaloneBuilder Preferences',
    'position':(133, 73),
    'size':(705, 395),
    'components': [

{'type':'TextField', 
    'name':'resEditPath', 
    'position':(205, 30), 
    'size':(405, -1), 
    'actionBindings':{}, 
    'userdata':'Select the location on your computer where the PythonCard resource editor is installed.', 
    },

{'type':'Button', 
    'name':'resEditPathBtn', 
    'position':(620, 25), 
    'size':(30, 30), 
    'actionBindings':{}, 
    'label':'...', 
    },

{'type':'Button', 
    'name':'resEditPathHelpBtn', 
    'position':(650, 25), 
    'size':(30, 30), 
    'actionBindings':{}, 
    'label':'?', 
    },

{'type':'TextField', 
    'name':'srcEditPath', 
    'position':(205, 60), 
    'size':(405, -1), 
    'actionBindings':{}, 
    'userdata':'Select the location on your computer where the PythonCard source code editor is installed.\n', 
    },

{'type':'Button', 
    'name':'srcEditPathBtn', 
    'position':(620, 55), 
    'size':(30, 30), 
    'actionBindings':{}, 
    'label':'...', 
    },

{'type':'Button', 
    'name':'srcEditPathHelpBtn', 
    'position':(650, 55), 
    'size':(30, 30), 
    'actionBindings':{}, 
    'label':'?', 
    },

{'type':'TextField', 
    'name':'txtEditPath', 
    'position':(205, 90), 
    'size':(405, -1), 
    'actionBindings':{}, 
    'userdata':'Select the location on your computer where the PythonCard source code editor is installed.\n', 
    },

{'type':'Button', 
    'name':'txtEditPathBtn', 
    'position':(620, 85), 
    'size':(30, 30), 
    'actionBindings':{}, 
    'label':'...', 
    },

{'type':'Button', 
    'name':'txtEditPathHelpBtn', 
    'position':(650, 85), 
    'size':(30, 30), 
    'actionBindings':{}, 
    'label':'?', 
    },

{'type':'TextField', 
    'name':'pixmapEditPath', 
    'position':(205, 120), 
    'size':(405, -1), 
    'actionBindings':{}, 
    'userdata':'Select the location on your computer where your preferred pixmap editor is installed.\n', 
    },

{'type':'Button', 
    'name':'pixmapEditPathBtn', 
    'position':(620, 115), 
    'size':(30, 30), 
    'actionBindings':{}, 
    'label':'...', 
    },

{'type':'Button', 
    'name':'pixmapEditPathHelpBtn', 
    'position':(650, 115), 
    'size':(30, 30), 
    'actionBindings':{}, 
    'label':'?', 
    },

{'type':'TextField', 
    'name':'compilerPath', 
    'position':(205, 150), 
    'size':(405, -1), 
    'actionBindings':{}, 
    'userdata':'Select the location on your computer where the Inno setup compiler is installed.', 
    },

{'type':'Button', 
    'name':'compilerPathBtn', 
    'position':(620, 145), 
    'size':(30, 30), 
    'actionBindings':{}, 
    'label':'...', 
    },

{'type':'Button', 
    'name':'compilerPathHelpBtn', 
    'position':(650, 145), 
    'size':(30, 30), 
    'actionBindings':{}, 
    'label':'?', 
    },

{'type':'TextField', 
    'name':'projectsPath', 
    'position':(205, 180), 
    'size':(405, -1), 
    'actionBindings':{}, 
    'userdata':'Select the location on your computer where you normally keep your PythonCard projects.', 
    },

{'type':'Button', 
    'name':'projectsPathBtn', 
    'position':(620, 175), 
    'size':(30, 30), 
    'actionBindings':{}, 
    'label':'...', 
    },

{'type':'Button', 
    'name':'projectsPathHelpBtn', 
    'position':(650, 175), 
    'size':(30, 30), 
    'actionBindings':{}, 
    'label':'?', 
    },

{'type':'Choice', 
    'name':'buildTool', 
    'position':(205, 245), 
    'size':(130, -1), 
    'actionBindings':{}, 
    'items':[u'py2exe', u'pyInstaller'], 
    'stringSelection':'pyInstaller', 
    'userdata':'Select the tool which you would prefer to use when building the executables for your projects.', 
    },

{'type':'Button', 
    'name':'buildToolHelpBtn', 
    'position':(650, 245), 
    'size':(30, 30), 
    'actionBindings':{}, 
    'label':'?', 
    },

{'type':'TextField', 
    'name':'installerPath', 
    'position':(205, 280), 
    'size':(405, -1), 
    'actionBindings':{}, 
    'userdata':'Select the location on your computer where the pyInstaller software is installed. Note that standaloneBuilder assumes that you have already configured this according to the documentation that comes with it.\n', 
    },

{'type':'Button', 
    'name':'installerPathBtn', 
    'position':(620, 275), 
    'size':(30, 30), 
    'actionBindings':{}, 
    'label':'...', 
    },

{'type':'Button', 
    'name':'installerPathHelpBtn', 
    'position':(650, 275), 
    'size':(30, 30), 
    'actionBindings':{}, 
    'label':'?', 
    },

{'type':'TextField', 
    'name':'appPublisher', 
    'position':(205, 310), 
    'size':(405, -1), 
    'actionBindings':{}, 
    'userdata':"Defines the name which will be used to add an 'AppPublisher' entry to your Inno script file. This name will appear when someone does a right click on your standalone executable and selects 'properties'.", 
    },

{'type':'Button', 
    'name':'appPublisherHelpBtn', 
    'position':(650, 305), 
    'size':(30, 30), 
    'actionBindings':{}, 
    'label':'?', 
    },

{'type':'Button', 
    'id':5100, 
    'name':'btnOK', 
    'position':(520, 355), 
    'actionBindings':{}, 
    'label':'OK', 
    },

{'type':'Button', 
    'id':5101, 
    'name':'btnCancel', 
    'position':(610, 355), 
    'actionBindings':{}, 
    'label':'Cancel', 
    },

{'type':'StaticText', 
    'name':'StaticText2', 
    'position':(80, 185), 
    'actionBindings':{}, 
    'text':'Projects directory:', 
    },

{'type':'StaticText', 
    'name':'StaticText7', 
    'position':(70, 155), 
    'actionBindings':{}, 
    'text':'Inno setup compiler:', 
    },

{'type':'StaticText', 
    'name':'StaticText5', 
    'position':(45, 125), 
    'actionBindings':{}, 
    'text':'Preferred pixmap editor:', 
    },

{'type':'StaticText', 
    'name':'StaticText9', 
    'position':(90, 95), 
    'actionBindings':{}, 
    'text':'Plain text editor:', 
    },

{'type':'StaticText', 
    'name':'StaticText4', 
    'position':(45, 65), 
    'actionBindings':{}, 
    'text':'PythonCard code editor:', 
    },

{'type':'StaticText', 
    'name':'StaticText3', 
    'position':(20, 35), 
    'actionBindings':{}, 
    'text':'PythonCard resource editor:', 
    },

{'type':'StaticBox', 
    'name':'StaticBox1', 
    'position':(10, 5), 
    'size':(685, 215), 
    'actionBindings':{}, 
    'label':'Paths to external files', 
    },

{'type':'StaticText', 
    'name':'StaticText6', 
    'position':(90, 315), 
    'actionBindings':{}, 
    'text':'Publisher name:', 
    },

{'type':'StaticText', 
    'name':'StaticText1', 
    'position':(75, 285), 
    'actionBindings':{}, 
    'text':'Path to pyInstaller:', 
    },

{'type':'StaticText', 
    'name':'StaticText8', 
    'position':(70, 255), 
    'actionBindings':{}, 
    'text':'Preferred build tool:', 
    },

{'type':'StaticBox', 
    'name':'StaticBox2', 
    'position':(10, 225), 
    'size':(685, 125), 
    'actionBindings':{}, 
    'label':'Other settings', 
    },

] # end components
} # end CustomDialog
