{'type':'CustomDialog',
    'name':'propertiesDialog',
    'title':'Project properties',
    'position':(555, 29),
    'size':(430, 395),
    'components': [

{'type':'TextField', 
    'name':'buildPath', 
    'position':(115, 5), 
    'size':(265, -1), 
    },

{'type':'Button', 
    'name':'buildPathBtn', 
    'position':(385, 5), 
    'size':(25, 22), 
    'label':'...', 
    },

{'type':'TextField', 
    'name':'distPath', 
    'position':(115, 40), 
    'size':(265, -1), 
    },

{'type':'Button', 
    'name':'distPathBtn', 
    'position':(385, 40), 
    'size':(25, 22), 
    'label':'...', 
    },

{'type':'TextField', 
    'name':'pixmapsPath', 
    'position':(115, 75), 
    'size':(265, -1), 
    },

{'type':'Button', 
    'name':'pixmapsPathBtn', 
    'position':(385, 75), 
    'size':(25, 22), 
    'label':'...', 
    },

{'type':'TextField', 
    'name':'tarballPath', 
    'position':(115, 110), 
    'size':(265, -1), 
    },

{'type':'Button', 
    'name':'tarballsPathBtn', 
    'position':(385, 110), 
    'size':(25, 22), 
    'label':'...', 
    },

{'type':'TextField', 
    'name':'appPublisher', 
    'position':(115, 145), 
    'size':(265, -1), 
    },

{'type':'TextField', 
    'name':'appURL', 
    'position':(115, 180), 
    'size':(265, -1), 
    },

{'type':'TextField', 
    'name':'appLicence', 
    'position':(115, 215), 
    'size':(265, -1), 
    },

{'type':'Button', 
    'name':'appLicenceBtn', 
    'position':(385, 215), 
    'size':(25, 22), 
    'label':'...', 
    },

{'type':'Choice', 
    'name':'buildType', 
    'position':(110, 250), 
    'size':(125, -1), 
    'items':[u'Single file', u'Single directory'], 
    'stringSelection':'Single directory', 
    },

{'type':'CheckBox', 
    'name':'asciiChk', 
    'position':(105, 285), 
    'label':'No encoding', 
    },

{'type':'CheckBox', 
    'name':'consoleChk', 
    'position':(220, 285), 
    'label':'Console', 
    },

{'type':'CheckBox', 
    'name':'compressChk', 
    'position':(315, 285), 
    'label':'Compress', 
    },

{'type':'CheckBox', 
    'name':'striplibsChk', 
    'position':(105, 305), 
    'label':'Strip libs (Linux)', 
    },

{'type':'CheckBox', 
    'name':'optimizeChk', 
    'position':(220, 305), 
    'label':'Optimize', 
    },

{'type':'CheckBox', 
    'name':'debugChk', 
    'position':(315, 305), 
    'label':'Debug', 
    },

{'type':'Button', 
    'id':5100, 
    'name':'btnOK', 
    'position':(10, 340), 
    'label':'OK', 
    },

{'type':'Button', 
    'id':5101, 
    'name':'btnCancel', 
    'position':(95, 340), 
    'label':'Cancel', 
    },

{'type':'StaticText', 
    'name':'StaticText9', 
    'position':(25, 220), 
    'text':'App licence file', 
    },

{'type':'StaticText', 
    'name':'StaticText8', 
    'position':(20, 185), 
    'text':'Application URL', 
    },

{'type':'StaticText', 
    'name':'StaticText7', 
    'position':(30, 150), 
    'text':'App publisher', 
    },

{'type':'StaticText', 
    'name':'StaticText6', 
    'position':(30, 285), 
    'text':'Build options', 
    },

{'type':'StaticText', 
    'name':'StaticText5', 
    'position':(15, 255), 
    'text':'Deployment type', 
    },

{'type':'StaticText', 
    'name':'StaticText4', 
    'position':(15, 115), 
    'text':'Tarballs directory', 
    },

{'type':'StaticText', 
    'name':'StaticText3', 
    'position':(15, 80), 
    'text':'Pixmaps directory', 
    },

{'type':'StaticText', 
    'name':'StaticText2', 
    'position':(5, 45), 
    'text':'Distribution directory', 
    },

{'type':'StaticText', 
    'name':'StaticText1', 
    'position':(30, 10), 
    'text':'Build directory', 
    },

] # end components
} # end CustomDialog
