{'application':{'type':'Application',
          'name':'codeEditor',
    'backgrounds': [
    {'type':'Background',
          'name':'bgCodeEditor',
          'title':'Code Editor R PythonCard Application',
          'size':(400, 300),
          'statusBar':1,
          'visible':0,
          'style':['resizeable'],

          'visible':0,
          'menubar': {'type':'MenuBar',
          'menus': [
              {'type':'Menu',
              'name':'menuFile',
              'label':'&File',
              'items': [
                  {'type':'MenuItem',
                   'name':'menuFileNewWindow',
                   'label':'New Window',
                  },
                  {'type':'MenuItem',
                   'name':'menuFileNew',
                   'label':'&New\tCtrl+N',
                  },
                  {'type':'MenuItem',
                   'name':'menuFileOpen',
                   'label':'&Open\tCtrl+O',
                  },
                  {'type':'MenuItem',
                   'name':'menuFileSave',
                   'label':'&Save\tCtrl+S',
                  },
                  {'type':'MenuItem',
                   'name':'menuFileSaveAs',
                   'label':'Save &As...',
                  },
                  {'type':'MenuItem',
                   'name':'fileSep1',
                   'label':'-',
                  },
                  {'type':'MenuItem',
                   'name':'menuFileCheckSyntax',
                   'label':'&Check Syntax (Module)\tAlt+F5',
                   'command':'checkSyntax',
                  },
                  {'type':'MenuItem',
                   'name':'menuFileRun',
                   'label':'&Run\tCtrl+R',
                   'command':'fileRun',
                  },
                  {'type':'MenuItem',
                   'name':'menuFileRunWithInterpreter',
                   'label':'Run with &interpreter\tCtrl+Shift+R',
                   'command':'fileRunWithInterpreter',
                  },
                  {'type':'MenuItem',
                   'name':'menuFileRunOptions',
                   'label':'Run Options...',
                   'command':'fileRunOptions',
                  },
                  {'type':'MenuItem',
                   'name':'fileSep2',
                   'label':'-',
                  },
                  {'type':'MenuItem',
                   'name':'menuFilePageSetup',
                   'label':'Page Set&up...',
                  },
                  {'type':'MenuItem',
                   'name':'menuFilePrint',
                   'label':'&Print...\tCtrl+P',
                  },
                  {'type':'MenuItem',
                   'name':'menuFilePrintPreview',
                   'label':'Print Pre&view',
                  },
                  {'type':'MenuItem',
                   'name':'fileSep2',
                   'label':'-',
                  },
                  {'type':'MenuItem',
                   'name':'menuFileExit',
                   'label':'E&xit\tAlt+X',
                   'command':'exit',
                  },
              ]
             },
             {'type':'Menu',
             'name':'Edit',
             'label':'&Edit',
             'items': [
                  {'type':'MenuItem',
                   'name':'menuEditUndo',
                   'label':'&Undo\tCtrl+Z',
                  },
                  {'type':'MenuItem',
                   'name':'menuEditRedo',
                   'label':'&Redo\tCtrl+Y',
                  },
                  {'type':'MenuItem',
                   'name':'editSep1',
                   'label':'-',
                  },
                  {'type':'MenuItem',
                   'name':'menuEditCut',
                   'label':'Cu&t\tCtrl+X',
                  },
                  {'type':'MenuItem',
                   'name':'menuEditCopy',
                   'label':'&Copy\tCtrl+C',
                  },
                  {'type':'MenuItem',
                   'name':'menuEditPaste',
                   'label':'&Paste\tCtrl+V',
                  },
                  {'type':'MenuItem',
                   'name':'editSep2',
                   'label':'-',
                  },
                  {'type':'MenuItem',
                   'name':'menuEditFind',
                   'label':'&Find...\tCtrl+F',
                   'command':'doEditFind',
                  },
                  {'type':'MenuItem',
                   'name':'menuEditFindNext',
                   'label':'&Find Next\tF3',
                   'command':'doEditFindNext',
                  },
                  {'type':'MenuItem',
                   'name':'menuEditFindFiles',
                   'label':'Find in Files...\tAlt+F3',
                   'command':'findFiles',
                  },
                  {'type':'MenuItem',
                   'name':'menuEditReplace',
                   'label':'&Replace...\tCtrl+H',
                   'command':'doEditFindReplace',
                  },
                  {'type':'MenuItem',
                   'name':'menuEditGoTo',
                   'label':'&Go To...\tCtrl+G',
                   'command':'doEditGoTo',
                  },
                  {'type':'MenuItem',
                   'name':'editSep3',
                   'label':'-',
                  },
                  {'type':'MenuItem',
                   'name':'menuEditReplaceTabs',
                   'label':'&Replace tabs with spaces',
                   'command':'doEditReplaceTabs',
                  },
                  {'type':'MenuItem',
                   'name':'editSep3',
                   'label':'-',
                  },
                  {'type':'MenuItem',
                   'name':'menuEditClear',
                   'label':'Cle&ar\tDel',
                  },
                  {'type':'MenuItem',
                   'name':'menuEditSelectAll',
                   'label':'Select A&ll\tCtrl+A',
                  },
                  {'type':'MenuItem',
                   'name':'editSep4',
                   'label':'-',
                  },
                  {'type':'MenuItem',
                   'name':'menuEditIndentRegion',
                   'label':'&Indent Region',
                   'command':'indentRegion',
                  },
                  {'type':'MenuItem',
                   'name':'menuEditDedentRegion',
                   'label':'&Dedent Region',
                   'command':'dedentRegion',
                  },
                  {'type':'MenuItem',
                   'name':'menuEditCommentRegion',
                   'label':'Comment &out region\tAlt+3',
                   'command':'commentRegion',
                  },
                  {'type':'MenuItem',
                   'name':'menuEditUncommentRegion',
                   'label':'U&ncomment region\tShift+Alt+3',
                   'command':'uncommentRegion',
                  },
              ]
             },
             {'type':'Menu',
             'name':'menuView',
             'label':'&View',
             'items': [
                  {'type':'MenuItem',
                   'name':'menuViewWhitespace',
                   'label':'&Whitespace',
                   'checkable':1,
                  },
                  {'type':'MenuItem',
                   'name':'menuViewIndentationGuides',
                   'label':'Indentation &guides',
                   'checkable':1,
                  },
                  {'type':'MenuItem',
                   'name':'menuViewRightEdgeIndicator',
                   'label':'&Right edge indicator',
                   'checkable':1,
                  },
                  {'type':'MenuItem',
                   'name':'menuViewEndOfLineMarkers',
                   'label':'&End-of-line markers',
                   'checkable':1,
                  },
                  {'type':'MenuItem',
                   'name':'menuViewFixedFont',
                   'label':'&Fixed Font',
                   'enabled':0,
                   'checkable':1,
                  },
                  {'type':'MenuItem',
                   'name':'viewSep1',
                   'label':'-',
                  },
                  {'type':'MenuItem',
                   'name':'menuViewLineNumbers',
                   'label':'&Line Numbers',
                   'checkable':1,
                   'checked':1,
                  },
                  {'type':'MenuItem',
                   'name':'menuViewCodeFolding',
                   'label':'&Code Folding',
                   'checkable':1,
                   'checked':0,
                  },
              ]
             },
             {'type':'Menu',
             'name':'menuFormat',
             'label':'F&ormat',
             'items': [
                  {'type':'MenuItem',
                   'name':'menuFormatStyles',
                   'label':'&Styles...',
                   'command':'doSetStyles',
                  },
                  {'type':'MenuItem',
                   'name':'menuFormatWrap',
                   'label':'&Wrap Lines',
                   'checkable':1,
                  },
              ]
             },
             {'type':'Menu',
             'name':'menuScriptlet',
             'label':'&Shell',
             'items': [
                  {'type':'MenuItem',
                   'name':'menuScriptletShell',
                   'label':'&Shell Window\tF5',
                  },
                  {'type':'MenuItem',
                   'name':'menuScriptletNamespace',
                   'label':'&Namespace Window\tF6',
                  },
                  {'type':'MenuItem',
                   'name':'scriptletSep1',
                   'label':'-',
                  },
                  {'type':'MenuItem',
                   'name':'menuScriptletSaveShellSelection',
                   'label':'Save Shell Selection...',
                  },
                  {'type':'MenuItem',
                   'name':'menuScriptletRunScriptlet',
                   'label':'Run Scriptlet...',
                  },
              ]
             },
             {'type':'Menu',
             'name':'menuHelp',
             'label':'&Help',
             'items': [
                  {'type':'MenuItem',
                   'name':'menuShellDocumentation',
                   'label':'&Shell Documentation...',
                   'command':'showShellDocumentation',
                  },
                  {'type':'MenuItem',
                   'name':'menuPythonCardDocumentation',
                   'label':'&PythonCard Documentation...\tF1',
                   'command':'showPythonCardDocumentation',
                  },
                  {'type':'MenuItem',
                   'name':'menuPythonDocumentation',
                   'label':'Python &Documentation...',
                   'command':'showPythonDocumentation',
                  },
                  {'type':'MenuItem',
                   'name':'helpSep1',
                   'label':'-',
                  },
                  {'type':'MenuItem',
                   'name':'menuHelpAbout',
                   'label':'&About codeEditor...',
                   'command':'doHelpAbout',
                  },
              ]
             },
         ]
     },
         'strings': {
         'saveAs':'Save As',
         'about':'About codeEditor...',
         'saveAsWildcard':'All files (*.*)|*.*|Python scripts (*.py;*.pyw)|*.pyw;*.PY;*.PYW;*.py|Text files (*.txt;*.text)|*.text;*.TXT;*.TEXT;*.txt|HTML and XML files (*.htm;*.html;*.xml)|*.htm;*.xml;*.HTM;*.HTML;*.XML;*.html',
         'chars':'chars',
         'gotoLine':'Goto line',
         'lines':'lines',
         'gotoLineNumber':'Goto line number:',
         'documentChangedPrompt':'The text in the %s file has changed.\n\nDo you want to save the changes?',
         'untitled':'Untitled',
         'sample':'codeEditor sample',
         'codeEditor':'codeEditor',
         'replaced':'Replaced %d occurances',
         'words':'words',
         'openFile':'Open file',
         'scriptletWildcard':'Python files (*.py)|*.py|All Files (*.*)|*.*',
         'document':'Document',
         },

         'components': [

{'type':'Choice', 
    'name':'popComponentNames', 
    },

{'type':'Choice', 
    'name':'popComponentEvents', 
    },

{'type':'CodeEditor', 
    'name':'document', 
    'position':(0, 0), 
    'size':(250, 100), 
    },

] # end components
} # end background
] # end backgrounds
} }
