@ECHO OFF
REM This file was generated by 'ProgGenerator'  

if exist "Start_Arduino_Result.txt" del "Start_Arduino_Result.txt"
COLOR 1F
ECHO    " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " "
ECHO    "    Zum                                                                  "
ECHO    "     PC                    Prog_Generator Ver. 3.3.2G          by Hardi  "
ECHO    "      \\                                                                 "
ECHO    "       \\                                                                "
ECHO    "    ____\\___________________                                            "
ECHO    "   |  | [_] | | [_] |[oo]    |  Achtung: Es muss der linke               "
ECHO    "   |  |     | |     |        |  Arduino mit dem PC verbunden             "
ECHO    "   |  |     | |     |        |  sein.                                    "
ECHO    "   |  | LED | |     |        |                                           "
ECHO    "   |  | Nano| |     |        |  Wenn alles gut geht, dann wird das       "
ECHO    "   |  |     | |     |        |  Fenster ohne eine weitere Meldung        "
ECHO    "   |  |     | |     |        |  geschlossen (Liest ja eh keiner).        "
ECHO    "   |  |_____| |_____| [O]    |                                           "
ECHO    "   |    [@] [@] [@]          |  Falls Probleme auftreten, dann wird      "
ECHO    "   |__________________[:::]__|  das angezeigt.                           "
ECHO    "                                                                         "
ECHO    " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " "

CHCP 65001 >NUL
ECHO|SET /p="Verzeichnis: "
CD
ECHO/

Call Start_AM328_Sub.cmd  2>&1 | find /v "Set log4j store directory" | find /v " StatusLogger " | find /v "serial.SerialDiscovery"
ECHO/

IF EXIST "Start_Arduino_Result.txt" (
   COLOR 4F
   ECHO   ****************************************
   ECHO    Da ist was schief gegangen ;-(
   ECHO   ****************************************
   Pause
   )
