@ECHO OFF
REM This file was generated by 'ProgGenerator'  

if exist "Start_Arduino_Result.txt" del "Start_Arduino_Result.txt"
COLOR 1E
ECHO    " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " "
ECHO    "        Zum                                                              "
ECHO    "         PC                Prog_Generator Ver. 3.3.2B         by Juergen "
ECHO    "          \\                                                   and Hardi "
ECHO    "           \\                                                            "
ECHO    "    ________\\_______________                                            "
ECHO    "   |    | # [_] # |  [oo]   _|  Achtung: Es wird nur ein ESP32           "
ECHO    "   |    |         |  DCC   |C|           Modul verwendet.                "
ECHO    "   |    | ::::::: |        |A|                                           "
ECHO    "   |    |  _____  |        |N|                                           "
ECHO    "   |    | |     | |         ~|  Wenn alles gut geht, dann wird das       "
ECHO    "   |    | |ESP32| |          |  Fenster ohne eine weitere Meldung        "
ECHO    "   |    | |_____| |          |  geschlossen (Liest ja eh keiner).        "
ECHO    "   |    |_________|   [O]    |                                           "
ECHO    "   |    [@] [@] [@]          |  Falls Probleme auftreten, dann wird      "
ECHO    "   |__________________[:::]__|  das angezeigt.                           "
ECHO    "                                                                         "
ECHO    " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " " "

CHCP 65001 >NUL
ECHO|SET /p="Verzeichnis: "
CD
ECHO.

Call Start_ESP32_Sub.cmd
ECHO.

IF EXIST "Start_Arduino_Result.txt" (
   COLOR 4F
   ECHO   ****************************************
   ECHO    Da ist was schief gegangen ;-(
   ECHO   ****************************************
   Pause
   )
