{'application':{'type':'Application',
          'name':'Template',
    'backgrounds': [
    {'type':'Background',
          'name':'bgTemplate',
          'title':'resourceEditor Multiple Components Editor',
          'size':(480, 577),
          'statusBar':1,

         'components': [

{'type':'StaticText', 
    'name':'stcNames', 
    'position':(10, 10), 
    'size':(84, -1), 
    'text':'Name  :  Class', 
    },

{'type':'List', 
    'name':'wComponentList', 
    'position':(7, 26), 
    'size':(163, 172), 
    'items':[], 
    },

{'type':'CheckBox', 
    'name':'Visible', 
    'position':(288, 27), 
    'size':(57, -1), 
    'label':'visible', 
    },

{'type':'CheckBox', 
    'name':'Enabled', 
    'position':(201, 27), 
    'label':'enabled', 
    },

{'type':'Button', 
    'name':'HorizontalCentres', 
    'position':(339, 142), 
    'size':(85, 25), 
    'label':'Centres', 
    },

{'type':'Button', 
    'name':'VerticalCentres', 
    'position':(364, 65), 
    'size':(42, 69), 
    'label':'Centres', 
    },

{'type':'Button', 
    'name':'Bottom', 
    'position':(243, 132), 
    'size':(53, -1), 
    'label':'Bottom', 
    },

{'type':'Button', 
    'name':'Top', 
    'position':(244, 78), 
    'size':(53, -1), 
    'label':'Top', 
    },

{'type':'Button', 
    'name':'Right', 
    'position':(287, 103), 
    'size':(53, -1), 
    'label':'Right', 
    },

{'type':'Button', 
    'name':'Left', 
    'position':(200, 104), 
    'size':(52, -1), 
    'label':'Left', 
    },

{'type':'StaticBox', 
    'name':'Align', 
    'position':(194, 53), 
    'size':(234, 132), 
    'label':'ALIGN', 
    },

{'type':'ImageButton', 
    'name':'SendToBack', 
    'position':(15, 255), 
    'size':(18, 24), 
    'border':'transparent', 
    'command':'componentSendBack', 
    'file':'images/send_to_back.png', 
    },

{'type':'ImageButton', 
    'name':'MoveBack', 
    'position':(45, 255), 
    'size':(18, 24), 
    'border':'transparent', 
    'command':'componentMoveBack', 
    'file':'images/move_back.png', 
    },

{'type':'ImageButton', 
    'name':'MoveForward', 
    'position':(75, 255), 
    'size':(18, 24), 
    'border':'transparent', 
    'command':'componentMoveForward', 
    'file':'images/move_forward.png', 
    },

{'type':'ImageButton', 
    'name':'SendToFront', 
    'position':(105, 255), 
    'size':(18, 24), 
    'border':'transparent', 
    'command':'componentBringFront', 
    'file':'images/send_to_front.png', 
    },

] # end components
} # end background
] # end backgrounds
} }
