{'application':{'type':'Application',
          'name':'Template',
    'backgrounds': [
    {'type':'Background',
          'name':'standaloneBuilder',
          'title':u'PythonCard standaloneBuilder',
          'size':(800, 610),
          'statusBar':1,

        'menubar': {'type':'MenuBar',
         'menus': [
             {'type':'Menu',
             'name':'menuFile',
             'label':'&File',
             'items': [
                  {'type':'MenuItem',
                   'name':'menuFileNew',
                   'label':'&New\tCtrl+N',
                   'command':'newBtn',
                  },
                  {'type':'MenuItem',
                   'name':'menuFileOpen',
                   'label':'&Open\tCtrl+O',
                   'command':'openBtn',
                  },
                  {'type':'MenuItem',
                   'name':'menuFileSave',
                   'label':'&Save\tCtrl+S',
                   'command':'saveBtn',
                  },
                  {'type':'MenuItem',
                   'name':'menuFileSaveAs',
                   'label':'Save &As...',
                  },
                  {'type':'MenuItem',
                   'name':'fileSep2',
                   'label':'-',
                  },
                  {'type':'MenuItem',
                   'name':'menuFileExit',
                   'label':'E&xit\tAlt+X',
                   'command':'menuFileExit',
                  },
              ]
             },
             {'type':'Menu',
             'name':'Edit',
             'label':'&Edit',
             'items': [
                  {'type':'MenuItem',
                   'name':'menuEditMainScript',
                   'label':u'&Main script...',
                   'command':'EditMainScript',
                  },
                  {'type':'MenuItem',
                   'name':'menuEditChglog',
                   'label':u'&Changelog...',
                   'command':'editChgLog',
                  },
                  {'type':'MenuItem',
                   'name':'menuEditReadme',
                   'label':u'&README...',
                   'command':'editReadme',
                  },
                  {'type':'MenuItem',
                   'name':'menuEditSpecfile',
                   'label':u'&Spec file...',
                   'command':'editSpecFile',
                  },
                  {'type':'MenuItem',
                   'name':'menuEditInnoFile',
                   'label':u'&Inno script...',
                   'command':'editInnoFile',
                  },
                  {'type':'MenuItem',
                   'name':'menuEditProps',
                   'label':u'&Project properties...',
                   'command':'editProps',
                  },
                  {'type':'MenuItem',
                   'name':'editSep1',
                   'label':'-',
                  },
                  {'type':'MenuItem',
                   'name':'menuEditPrefs',
                   'label':u'&Preferences...',
                   'command':'editPrefs',
                  },
              ]
             },
             {'type':'Menu',
             'name':'menuTools',
             'label':'&Tools',
             'items': [
                  {'type':'MenuItem',
                   'name':'menuToolsLogAdd',
                   'label':u'A&dd changelog entry...\tShift++',
                   'command':'menuToolsLogAdd',
                  },
                  {'type':'MenuItem',
                   'name':'menuToolsChkImport',
                   'label':u'&Check component imports',
                   'command':'menuToolsChkImport',
                  },
                  {'type':'MenuItem',
                   'name':'toolSep1',
                   'label':'-',
                  },
                  {'type':'MenuItem',
                   'name':'menuToolsAddScript',
                   'label':u'Add &script...',
                   'command':'addScript',
                  },
                  {'type':'MenuItem',
                   'name':'menuToolsAddResource',
                   'label':u'Add &resource...',
                   'command':'addResource',
                  },
                  {'type':'MenuItem',
                   'name':'menuToolsAddPixmap',
                   'label':u'Add &pixmap...',
                   'command':'addPixmap',
                  },
                  {'type':'MenuItem',
                   'name':'menuToolsAddOther',
                   'label':u'Add &other...',
                   'command':'addOther',
                  },
                  {'type':'MenuItem',
                   'name':'toolSep2',
                   'label':u'-',
                  },
                  {'type':'MenuItem',
                   'name':'menuToolsRunMain',
                   'label':u'Run &main script',
                   'command':'runMainScript',
                  },
                  {'type':'MenuItem',
                   'name':'toolSep3',
                   'label':u'-',
                  },
                  {'type':'MenuItem',
                   'name':'menuToolsRebuild',
                   'label':'R&ebuild\tCtrl+R',
                   'command':'rebuildCmd',
                  },
                  {'type':'MenuItem',
                   'name':'menuToolsRelease',
                   'label':u'&Release\tCtrl+M',
                   'command':'releaseCmd',
                  },
              ]
             },
             {'type':'Menu',
             'name':'menuHelp',
             'label':'&Help',
             'items': [
                  {'type':'MenuItem',
                   'name':'menuHelpManual',
                   'label':u'&Manual',
                   'command':'menuHelpManual',
                  },
                  {'type':'MenuItem',
                   'name':'menuHelpAbout',
                   'label':u'&About standaloneBuilder...',
                   'command':'menuHelpAbout',
                  },
              ]
             },
         ]
     },
         'strings': {
         u'testString':u'This is a test string',
         },

         'components': [

{'type':'Button', 
    'name':'mainScriptEditBtn', 
    'position':(375, 120), 
    'size':(52, 25), 
    'actionBindings':{}, 
    'command':'EditMainScript', 
    'font':{'faceName': u'Sans', 'size': 8}, 
    'label':'Edit...', 
    'toolTip':'Edit the main script', 
    },

{'type':'StaticText', 
    'name':'versionString', 
    'position':(560, 125), 
    'actionBindings':{}, 
    'text':'n/a', 
    },

{'type':'ImageButton', 
    'name':'newBtn', 
    'position':(5, 5), 
    'size':(38, 38), 
    'actionBindings':{}, 
    'backgroundColor':(255, 255, 255), 
    'border':'3d', 
    'command':'newBtn', 
    'file':'pixmaps/new.png', 
    'toolTip':'Create a new project', 
    'userdata':'frozen', 
    },

{'type':'ImageButton', 
    'name':'openBtn', 
    'position':(40, 5), 
    'size':(38, 38), 
    'actionBindings':{}, 
    'backgroundColor':(255, 255, 255), 
    'border':'3d', 
    'command':'openBtn', 
    'file':'pixmaps/open.png', 
    'toolTip':'Open an existing project', 
    'userdata':'frozen', 
    },

{'type':'ImageButton', 
    'name':'saveBtn', 
    'position':(75, 5), 
    'size':(38, 38), 
    'actionBindings':{}, 
    'backgroundColor':(255, 255, 255), 
    'border':'3d', 
    'command':'saveBtn', 
    'file':'pixmaps/save.png', 
    'toolTip':'Save the current project', 
    'userdata':'frozen', 
    },

{'type':'ImageButton', 
    'name':'prefsBtn', 
    'position':(705, 5), 
    'size':(38, 38), 
    'actionBindings':{}, 
    'backgroundColor':(255, 255, 255), 
    'border':'3d', 
    'command':'editPrefs', 
    'file':'pixmaps/prefs.png', 
    'toolTip':'standaloneBuilder preferences', 
    'userdata':'frozen', 
    },

{'type':'ImageButton', 
    'name':'quitBtn', 
    'position':(750, 5), 
    'size':(38, 38), 
    'actionBindings':{}, 
    'backgroundColor':(255, 255, 255), 
    'border':'3d', 
    'command':'quitBtn', 
    'file':'pixmaps/exit.png', 
    'toolTip':'Quit the program', 
    'userdata':'frozen', 
    },

{'type':'TextField', 
    'name':'projectName', 
    'position':(95, 60), 
    'size':(250, -1), 
    'actionBindings':{}, 
    },

{'type':'TextField', 
    'name':'projectIcon', 
    'position':(500, 60), 
    'size':(250, -1), 
    'actionBindings':{}, 
    },

{'type':'Button', 
    'name':'iconBtn', 
    'position':(755, 60), 
    'size':(25, 25), 
    'actionBindings':{}, 
    'label':'...', 
    },

{'type':'TextField', 
    'name':'baseDir', 
    'position':(95, 90), 
    'size':(250, -1), 
    'actionBindings':{}, 
    },

{'type':'Button', 
    'name':'baseDirBtn', 
    'position':(350, 90), 
    'size':(25, 25), 
    'actionBindings':{}, 
    'label':'...', 
    },

{'type':'TextField', 
    'name':'projectDesc', 
    'position':(500, 90), 
    'size':(250, -1), 
    'actionBindings':{}, 
    },

{'type':'TextField', 
    'name':'mainScript', 
    'position':(95, 120), 
    'size':(250, -1), 
    'actionBindings':{}, 
    },

{'type':'Button', 
    'name':'mainScriptBtn', 
    'position':(350, 120), 
    'size':(25, 25), 
    'actionBindings':{}, 
    'label':'...', 
    },

{'type':'StaticBox', 
    'name':'StaticBox2', 
    'position':(5, 165), 
    'size':(380, 160), 
    'actionBindings':{}, 
    'label':'Script files:', 
    },

{'type':'List', 
    'name':'scriptList', 
    'position':(15, 180), 
    'size':(360, 100), 
    'actionBindings':{}, 
    'items':[], 
    },

{'type':'Button', 
    'name':'scriptAddBtn', 
    'position':(15, 285), 
    'actionBindings':{}, 
    'command':'addScript', 
    'label':'Add...', 
    },

{'type':'Button', 
    'name':'scriptDelBtn', 
    'position':(100, 285), 
    'actionBindings':{}, 
    'label':'Remove', 
    },

{'type':'Button', 
    'name':'scriptEditBtn', 
    'position':(185, 285), 
    'actionBindings':{}, 
    'label':'Edit...', 
    },

{'type':'Button', 
    'name':'scriptDelAllBtn', 
    'position':(295, 285), 
    'actionBindings':{}, 
    'label':'Clear all', 
    },

{'type':'StaticBox', 
    'name':'StaticBox3', 
    'position':(405, 165), 
    'size':(380, 160), 
    'actionBindings':{}, 
    'label':'Resource files:', 
    },

{'type':'List', 
    'name':'resList', 
    'position':(415, 180), 
    'size':(360, 100), 
    'actionBindings':{}, 
    'items':[], 
    },

{'type':'Button', 
    'name':'resAddBtn', 
    'position':(415, 285), 
    'actionBindings':{}, 
    'command':'addResource', 
    'label':'Add..', 
    },

{'type':'Button', 
    'name':'resDelBtn', 
    'position':(500, 285), 
    'actionBindings':{}, 
    'label':'Remove', 
    },

{'type':'Button', 
    'name':'resEditBtn', 
    'position':(585, 285), 
    'actionBindings':{}, 
    'label':'Edit...', 
    },

{'type':'Button', 
    'name':'resDelAllBtn', 
    'position':(695, 285), 
    'actionBindings':{}, 
    'label':'Clear all', 
    },

{'type':'StaticBox', 
    'name':'StaticBox4', 
    'position':(5, 325), 
    'size':(380, 160), 
    'actionBindings':{}, 
    'label':'Pixmap files:', 
    },

{'type':'List', 
    'name':'pixmapList', 
    'position':(15, 340), 
    'size':(360, 100), 
    'actionBindings':{}, 
    'items':[], 
    },

{'type':'Button', 
    'name':'pixmapAddBtn', 
    'position':(15, 445), 
    'actionBindings':{}, 
    'command':'addPixmap', 
    'label':'Add...', 
    },

{'type':'Button', 
    'name':'pixmapDelBtn', 
    'position':(100, 445), 
    'actionBindings':{}, 
    'label':'Remove', 
    },

{'type':'Button', 
    'name':'pixmapEditBtn', 
    'position':(185, 445), 
    'actionBindings':{}, 
    'label':'Edit...', 
    },

{'type':'Button', 
    'name':'pixmapDelAllBtn', 
    'position':(295, 445), 
    'actionBindings':{}, 
    'label':'Clear all', 
    },

{'type':'StaticBox', 
    'name':'StaticBox5', 
    'position':(405, 325), 
    'size':(380, 160), 
    'actionBindings':{}, 
    'label':'Other files:', 
    },

{'type':'List', 
    'name':'otherList', 
    'position':(415, 340), 
    'size':(360, 100), 
    'actionBindings':{}, 
    'items':[], 
    },

{'type':'Button', 
    'name':'docAddBtn', 
    'position':(415, 445), 
    'actionBindings':{}, 
    'command':'addOther', 
    'label':'Add...', 
    },

{'type':'Button', 
    'name':'docDelBtn', 
    'position':(500, 445), 
    'actionBindings':{}, 
    'label':'Remove', 
    },

{'type':'Button', 
    'name':'docEditBtn', 
    'position':(585, 445), 
    'actionBindings':{}, 
    'label':'Edit...', 
    },

{'type':'Button', 
    'name':'docDelAllBtn', 
    'position':(695, 445), 
    'actionBindings':{}, 
    'label':'Clear all', 
    },

{'type':'Button', 
    'name':'propertiesBtn', 
    'position':(15, 490), 
    'size':(85, -1), 
    'actionBindings':{}, 
    'command':'editProps', 
    'label':'Properties...', 
    'toolTip':'Change your projects properties', 
    },

{'type':'Button', 
    'name':'changelogBtn', 
    'position':(100, 490), 
    'size':(85, -1), 
    'actionBindings':{}, 
    'command':'editChgLog', 
    'label':'Changelog...', 
    'toolTip':'Edit the changelog file', 
    },

{'type':'Button', 
    'name':'readmeBtn', 
    'position':(100, 525), 
    'actionBindings':{}, 
    'command':'editReadme', 
    'label':'README...', 
    'toolTip':'Edit the README file', 
    },

{'type':'Button', 
    'name':'specBtn', 
    'position':(185, 490), 
    'actionBindings':{}, 
    'command':'editSpecFile', 
    'label':'Spec file...', 
    'toolTip':'Edit the applications spec file', 
    },

{'type':'Button', 
    'name':'innoBtn', 
    'position':(185, 525), 
    'size':(85, -1), 
    'actionBindings':{}, 
    'command':'editInnoFile', 
    'label':'Inno script...', 
    'toolTip':'Edit the Inno setup script for your application', 
    },

{'type':'Button', 
    'name':'runBtn', 
    'position':(295, 490), 
    'actionBindings':{}, 
    'command':'runMainScript', 
    'label':'Run...', 
    'toolTip':'Run the application', 
    },

{'type':'Button', 
    'name':'rebuildBtn', 
    'position':(695, 490), 
    'actionBindings':{}, 
    'command':'rebuildCmd', 
    'label':'Rebuild', 
    'toolTip':'Rebuild the standalone version of your application', 
    'userdata':'frozen', 
    },

{'type':'Button', 
    'name':'releaseBtn', 
    'position':(695, 525), 
    'actionBindings':{}, 
    'command':'releaseCmd', 
    'label':'Release', 
    'toolTip':'Make a release of your finished application', 
    'userdata':'frozen', 
    },

{'type':'StaticBox', 
    'name':'StaticBox1', 
    'position':(5, 45), 
    'size':(780, 115), 
    'actionBindings':{}, 
    'label':'Project:', 
    },

{'type':'StaticText', 
    'name':'StaticText5', 
    'position':(15, 125), 
    'actionBindings':{}, 
    'text':'Main script', 
    },

{'type':'StaticText', 
    'name':'StaticText4', 
    'position':(420, 95), 
    'actionBindings':{}, 
    'text':'Description', 
    },

{'type':'StaticText', 
    'name':'StaticText9', 
    'position':(430, 65), 
    'actionBindings':{}, 
    'text':'Icon (Win)', 
    },

{'type':'StaticText', 
    'name':'StaticText8', 
    'position':(500, 125), 
    'actionBindings':{}, 
    'text':'Version', 
    },

{'type':'StaticText', 
    'name':'StaticText7', 
    'position':(15, 95), 
    'actionBindings':{}, 
    'text':'Directory', 
    },

{'type':'StaticText', 
    'name':'StaticText6', 
    'position':(15, 65), 
    'actionBindings':{}, 
    'text':'Name', 
    },

] # end components
} # end background
] # end backgrounds
} }
